import pandas as pd
import zipfile
import tempfile
import time
import base64
import os

def get_object_fields(sf_instance, object_name):
    """
    Fetches the field describe for an object and returns a dictionary of field definitions.
    """
    try:
        describe_res = getattr(sf_instance, object_name).describe()
        return {f['name']: f for f in describe_res['fields']}
    except Exception as e:
        print(f"Error describing {object_name}: {e}")
        return {}

def compare_schemas(source_sf, target_sf, object_list):
    """
    Compares the schema between Source and Target for a list of objects.
    Returns a Pandas DataFrame representing missing fields on the Target.
    """
    diff_data = []
    
    for obj in object_list:
        src_fields = get_object_fields(source_sf, obj)
        tgt_fields = get_object_fields(target_sf, obj)
        
        for field_name, src_attr in src_fields.items():
            if field_name not in tgt_fields:
                diff_data.append({
                    "Deploy": False,
                    "Object": obj,
                    "Field Name": field_name,
                    "Label": src_attr['label'],
                    "Type": src_attr['type'],
                    "Length": src_attr.get('length', ''),
                    "Status": "Missing on Target",
                    "Is_Custom": field_name.endswith('__c')
                })
            else:
                # Optionally check if length/type mismatches
                tgt_attr = tgt_fields[field_name]
                if src_attr['type'] != tgt_attr['type']:
                    diff_data.append({
                        "Deploy": False,
                        "Object": obj,
                        "Field Name": field_name,
                        "Label": src_attr['label'],
                        "Type": f"{src_attr['type']} -> {tgt_attr['type']}",
                        "Status": "Type Mismatch",
                        "Is_Custom": False # Can't deploy standard type mismatches via tooling
                    })
    
    return pd.DataFrame(diff_data)

def get_external_id_candidates(sf_instance, object_name):
    """
    Returns a list of fields on the object that have 'External ID' set to True.
    """
    fields = get_object_fields(sf_instance, object_name)
    return [f_name for f_name, f_attr in fields.items() if f_attr.get('externalId')]

def deploy_external_id_field(target_sf, object_name):
    """
    Deploys the Migration_External_ID__c field to the specified Object on the Target Org
    using the Salesforce Tooling API (JSON).
    """
    try:
        full_name = f"{object_name}.Migration_External_ID__c"
        metadata = {
            "label": "Migration External ID",
            "type": "Text",
            "length": 255,
            "externalId": True,
            "unique": True,
            "caseSensitive": False,
            "required": False,
            "description": "Generated by SF-Data-Bridge for relationship mapping."
        }
        
        payload = {
            "FullName": full_name,
            "Metadata": metadata
        }
        
        # Tooling API POST for CustomField
        target_sf.toolingexecute('sobjects/CustomField/', method='POST', json=payload)
        return True, None
    except Exception as e:
        err_str = str(e)
        if "DUPLICATE_DEVELOPER_NAME" in err_str:
            return True, None # Already exists
        return False, err_str

def deploy_selected_metadata(source_sf, target_sf, selected_rows):
    """
    Deploys selected custom fields from Source to Target using Tooling API.
    """
    success_count = 0
    errors = []
    
    for row in selected_rows:
        if not row.get('Deploy') or not row.get('Is_Custom'):
            continue
            
        obj = row['Object']
        field = row['Field Name']
        
        try:
            # 1. Fetch Metadata from Source
            dev_name = field.replace('__c', '')
            # Tooling API query needs to be URL encoded or handled by tooling_execute logic
            # simple-salesforce toolingexecute doesn't automatically urlencode the 'action' string if it's a query
            query = f"SELECT Metadata FROM CustomField WHERE DeveloperName='{dev_name}' AND TableEnumOrId='{obj}'"
            encoded_query = query.replace(' ', '+').replace("'", "%27")
            res = source_sf.toolingexecute(f"query?q={encoded_query}")
            
            if not res.get('records'):
                errors.append(f"Field {field} on {obj}: Not found in Source Tooling metadata.")
                continue
                
            metadata = res['records'][0]['Metadata']
            
            # 2. Deploy to Target
            full_name = f"{obj}.{field}"
            # Tooling API POST for CustomField
            payload = {
                "FullName": full_name,
                "Metadata": metadata
            }
            
            target_sf.toolingexecute('sobjects/CustomField/', method='POST', json=payload)
            success_count += 1
            
        except Exception as e:
            err_str = str(e)
            if "DUPLICATE_DEVELOPER_NAME" in err_str:
                # Treat as success if the field already exists as intended
                success_count += 1
            else:
                errors.append(f"Field {field} on {obj}: {err_str}")
            
    return success_count, errors
